name: "Build and Push Docker"
description: "Build a container image and Pushes it to Docker registry"

inputs:
  docker_username:
    description: "Username for Docker registry"
    required: true
  docker_password:
    description: "Password for Docker registry"
    required: true
  image_name:
    description: "Name of the image to push"
    required: true
  build_args:
    description: "A list of extra build args. Default: []"
    required: false
  push:
    required: true
    description: "Wether to push the image or not"
  target: 
    required: true
    description: "Target image in multistage build"
  tag: 
    required: false
    description: "Tag to add to Docker Image"
  context:
    required: false
    description: "Context for the Docker build"

runs:
  using: "composite"
  steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: false

      - name: Login to the Registry
        uses: docker/login-action@v1
        with:
          username: ${{inputs.docker_username}}
          password: ${{inputs.docker_password}}
      
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Generate Docker Metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ inputs.docker_username }}/${{ inputs.image_name }}
          # generate Docker tags based on the following events/attributes
          tags: |
            ${{ inputs.tag }}
            ${{ github.sha }}
            latest

      - name: Set Context
        shell: bash
        id: set-context
        run: |
          if [ ! -z ${{inputs.context}} ]; then
            echo "Using provided Context"
            echo "::set-output name=context::${{inputs.context}}"
          else
            echo "Context not provided, using current directory"
            echo "::set-output name=context::./"
          fi

      - name: Build and Push the Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.set-context.outputs.context }}
          push: ${{ inputs.push }}
          tags: ${{ steps.metadata.outputs.tags }}
          build-args: ${{ inputs.build_args }}
          target: ${{ inputs.target }}
          cache-from: |
            type=gha,scope=${{inputs.image_name}}
          cache-to: |
            type=gha,scope=${{inputs.image_name}},mode=max
