name: "Test and Publish Results"
description: "Test using the Dockerfile and publish results to PR"

inputs:
  image_name:
    description: "Name of the image to push"
    required: true
  build_args:
    description: "A list of extra build args. Default: []"

runs:
  using: "composite"
  steps:
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Lint
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{inputs.image_name}}:test
          build-args: ${{ inputs.build_args }}
          target: lint
          cache-from: |
            type=gha,scope=lint
          cache-to: |
            type=gha,scope=lint,mode=max

      - name: Test
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{inputs.image_name}}:test
          build-args: ${{ inputs.build_args }}
          target: test-results
          outputs: "type=local,dest=out"
          cache-from: |
            type=gha,scope=test
            type=gha,scope=lint
          cache-to: |
            type=gha,scope=test,mode=max
      
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: out

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: out/**/*.xml

