name: "Lint"
description: "Lint Step"

inputs:
  lint_path:
    required: true
    description: "Paths to Lint"

runs:
  using: "composite"
  steps:

  - name: Code Formatting
    working-directory: ${{ github.repository }}
    shell: bash
    run: |
      poetry run black --config ./pyproject.toml --check ${{ inputs.lint_path }}
